USE [RestaurantReservationProject]
GO

TRUNCATE TABLE Employees;

INSERT INTO [dbo].[Employees]
           ([RestaurantId]
           ,[FirstName]
           ,[LastName]
           ,[Position])
     VALUES
        (25, 'Filide', 'Mitchelson', 'VIPOrdersWaiter'),
        (20, 'Carmencita', 'Ybarra', 'VIPOrdersWaiter'),
        (26, 'Norrie', 'Chastaing', 'StandardWaiter'),
        (38, 'Dicky', 'Brownsea', 'AssistantWaiter'),
        (3, 'Tiertza', 'Vickarman', 'StandardWaiter'),
        (8, 'Hakim', 'Elwel', 'StandardWaiter'),
        (4, 'Kissie', 'Romain', 'StandardWaiter'),
        (19, 'Martynne', 'Moss', 'VIPOrdersWaiter'),
        (8, 'Pauli', 'Shave', 'StandardWaiter'),
        (19, 'Richy', 'Freeth', 'StandardWaiter'),
        (33, 'Beale', 'Houlson', 'StandardWaiter'),
        (5, 'Theobald', 'Biasi', 'VIPOrdersWaiter'),
        (29, 'Fields', 'Hutsby', 'VIPOrdersWaiter'),
        (15, 'Luigi', 'Nealey', 'AssistantWaiter'),
        (4, 'Tommy', 'Scandroot', 'StandardWaiter'),
        (31, 'Skipton', 'Gwatkins', 'VIPOrdersWaiter'),
        (28, 'Jillane', 'Fessions', 'StandardWaiter'),
        (1, 'Julietta', 'Messingham', 'StandardWaiter'),
        (35, 'Illa', 'Holsey', 'StandardWaiter'),
        (34, 'Samara', 'Karleman', 'StandardWaiter'),
        (25, 'Lisetta', 'Mynott', 'AssistantWaiter'),
        (13, 'Richmond', 'Wagge', 'AssistantWaiter'),
        (38, 'Jammie', 'Hiddsley', 'StandardWaiter'),
        (3, 'Umberto', 'Slyne', 'StandardWaiter'),
        (14, 'Elena', 'Wyburn', 'AssistantWaiter'),
        (32, 'Vittoria', 'Syers', 'AssistantWaiter'),
        (34, 'Cori', 'Bradborne', 'StandardWaiter'),
        (1, 'Tresa', 'Smellie', 'StandardWaiter'),
        (24, 'Alicia', 'Hames', 'VIPOrdersWaiter'),
        (21, 'Simonette', 'Pieter', 'AssistantWaiter'),
        (32, 'Perla', 'Stean', 'AssistantWaiter'),
        (32, 'Foster', 'Ivimy', 'AssistantWaiter'),
        (10, 'Matthew', 'Gunston', 'StandardWaiter'),
        (29, 'Ibbie', 'Pylkynyton', 'AssistantWaiter'),
        (1, 'Annissa', 'Sabater', 'StandardWaiter'),
        (23, 'Gawen', 'Tomkinson', 'VIPOrdersWaiter'),
        (30, 'Ozzy', 'Fensome', 'AssistantWaiter'),
        (37, 'Garvey', 'Primo', 'StandardWaiter'),
        (4, 'Lisha', 'Gradwell', 'AssistantWaiter'),
        (24, 'Yuma', 'Gendrich', 'StandardWaiter'),
        (10, 'Dinny', 'Osgarby', 'AssistantWaiter'),
        (25, 'Keane', 'Maraga', 'AssistantWaiter'),
        (4, 'Zachariah', 'D''Avaux', 'AssistantWaiter'),
        (32, 'Carree', 'Pendred', 'AssistantWaiter'),
        (25, 'Lurette', 'Riach', 'AssistantWaiter'),
        (28, 'Gray', 'Cobleigh', 'StandardWaiter'),
        (29, 'Roselin', 'McAneny', 'StandardWaiter'),
        (2, 'Noelani', 'Blannin', 'AssistantWaiter'),
        (38, 'Sharity', 'Baldetti', 'AssistantWaiter'),
        (30, 'Meier', 'Marder', 'AssistantWaiter'),
        (11, 'Thurstan', 'Frossell', 'AssistantWaiter'),
        (5, 'Jillene', 'Cressor', 'StandardWaiter'),
        (21, 'Paulina', 'Polycote', 'AssistantWaiter'),
        (6, 'Arty', 'Berrigan', 'StandardWaiter'),
        (24, 'Charleen', 'Acres', 'AssistantWaiter'),
        (17, 'Morty', 'Gullane', 'VIPOrdersWaiter'),
        (13, 'Dave', 'Deeney', 'StandardWaiter'),
        (18, 'Adam', 'Kopman', 'StandardWaiter'),
        (21, 'Anita', 'Barde', 'StandardWaiter'),
        (5, 'Merrel', 'Caselli', 'VIPOrdersWaiter'),
        (9, 'Darrelle', 'Lawleff', 'AssistantWaiter'),
        (17, 'Sidonnie', 'Cufflin', 'StandardWaiter'),
        (30, 'Abigail', 'Dumbleton', 'AssistantWaiter'),
        (2, 'Kimmi', 'Orringe', 'VIPOrdersWaiter'),
        (37, 'Laurene', 'Igglesden', 'StandardWaiter'),
        (29, 'Rori', 'Ridgers', 'StandardWaiter'),
        (6, 'Maddie', 'Howship', 'AssistantWaiter'),
        (11, 'Odelle', 'Urrey', 'StandardWaiter'),
        (7, 'Othello', 'Brugden', 'StandardWaiter'),
        (32, 'Lynea', 'Geraudy', 'StandardWaiter'),
        (16, 'Way', 'Birkenhead', 'AssistantWaiter'),
        (19, 'Talia', 'Patel', 'VIPOrdersWaiter'),
        (34, 'Carmelia', 'Ottey', 'AssistantWaiter'),
        (19, 'Malcolm', 'Capelin', 'AssistantWaiter'),
        (27, 'Dale', 'Bonavia', 'VIPOrdersWaiter'),
        (26, 'Ashlen', 'Basketter', 'AssistantWaiter'),
        (7, 'Hyacintha', 'Megany', 'VIPOrdersWaiter'),
        (39, 'Roz', 'Game', 'VIPOrdersWaiter'),
        (19, 'Padraic', 'Mardlin', 'AssistantWaiter'),
        (10, 'Gwenette', 'McKeon', 'StandardWaiter'),
        (8, 'Jenine', 'Meigh', 'AssistantWaiter'),
        (15, 'Allis', 'Laba', 'AssistantWaiter'),
        (9, 'Brett', 'Gillivrie', 'StandardWaiter'),
        (21, 'Dede', 'Whild', 'StandardWaiter'),
        (12, 'Meryl', 'Claxson', 'StandardWaiter'),
        (13, 'Jammie', 'Slyvester', 'StandardWaiter'),
        (38, 'Shelba', 'Caghy', 'AssistantWaiter'),
        (35, 'Carmel', 'Taree', 'StandardWaiter'),
        (11, 'Samuel', 'Rainton', 'AssistantWaiter'),
        (14, 'Felisha', 'Pettifer', 'VIPOrdersWaiter'),
        (10, 'Cherlyn', 'Akid', 'AssistantWaiter'),
        (39, 'Alisander', 'Rehorek', 'StandardWaiter'),
        (17, 'Haroun', 'Eldridge', 'StandardWaiter'),
        (5, 'Hally', 'Jedrzejczyk', 'StandardWaiter'),
        (18, 'Marlene', 'Ivamy', 'StandardWaiter'),
        (13, 'Dael', 'Neicho', 'StandardWaiter'),
        (7, 'Jacky', 'Posselwhite', 'AssistantWaiter'),
        (10, 'Demetrius', 'Alesio', 'AssistantWaiter'),
        (33, 'Yard', 'Larvor', 'AssistantWaiter'),
        (15, 'Rubetta', 'Wolfendell', 'StandardWaiter');
GO


